nome = input("Digite seu nome: ")
print("Olá, " + nome + "! Bem-vindo ao curso de Python!")
idade = int(input("Digite sua idade: "))
#print(str(type(idade)))
#idade = int(idade)
#print(str(type(idade)))
print(nome, ", você tem ", idade, " anos.")
altura = float(input("Digite sua altura em metros (ex: 1.75): "))
print(nome, ", você tem ", idade, " anos e ", altura, " metros de altura.")
